package se.kth.karamel.common.util.settings;


//import java.util.ArrayList;
import java.util.EnumSet;
import java.util.HashMap;
//import java.util.List;
import java.util.Map;

/**
 * Created by Alberto on 2015-05-14.
 */
public enum OcciSetting {

  OCCI_DEFAULT_USERNAME("default username here!"),
  OCCI_DEFAULT_USER_CERTIFICATE_PATH("default region here!"),
  OCCI_DEFAULT_CERTIFICATE_DIR("default flavor here!"),
  OCCI_DEFAULT_ENDPOINT("default username here!"),
  OCCI_DEFAULT_IMAGE("default image here!"),
  
  OCCI_USERNAME("default username here!"),
  OCCI_USER_CERTIFICATE_PATH(""),
  OCCI_CERTIFICATE_DIR("default flavor here!"),
  OCCI_ENDPOINT("default username here!"),
  OCCI_IMAGE("default image here!");

  /*OCCI_ACCESSKEY_KEY("occi.access.key"),
  OCCI_KEYPAIR_NAME_KEY("occi.keypair.name"),
  OCCI_RETRY_INTERVAL("5000"),
  OCCI_MAX_FORK_VMS_PER_REQUEST("50");*/

  private static final Map<String, OcciSetting> lookup
          = new HashMap<String, OcciSetting>();

  static {
    for (OcciSetting s : EnumSet.allOf(OcciSetting.class))
      lookup.put(s.getParameter(), s);
  }

  private String parameter;

  private OcciSetting(String parameter) {
    this.parameter = parameter;
  }

  public static OcciSetting get(String parameter) {
    return lookup.get(parameter);
  }
  
  public String getParameter() {
    return parameter;
  }

/*  public static final String OCCI_UNIQUE_GROUP_NAME(String clusterName, String groupName) {
    return (SystemSetting.USER_NAME.getParameter() + "-" + clusterName + "-" + groupName).toLowerCase();
  }

  public static final String OCCI_KEYPAIR_NAME(String clusterName, String region) {
    return (SystemSetting.USER_NAME.getParameter() + "-" + clusterName).toLowerCase();
  }

  public static final String OCCI_UNIQUE_GROUP_DESCRIPTION(String clusterName, String groupName) {
    return OCCI_UNIQUE_GROUP_NAME(clusterName, groupName) + "generated by karamel occi launcher";
  }

  public static final List<String> OCCI_UNIQUE_VM_NAMES(String clusterName, String groupName, int size) {
    List<String> names = new ArrayList<>();
    for (int i = 1; i <= size; i++) {
      names.add(OCCI_UNIQUE_GROUP_NAME(clusterName, groupName) + "-" + i);
    }
    return names;
  }*/


  
}
